/**
 * Check Point Output Generator — Enhanced
 * Reads the upgraded IR schema and generates Check Point Management CLI script.
 */

export class OutputCheckpointGenerator {
    constructor(parsedData) {
        this.data = parsedData;
        this.output = [];
    }

    generate() {
        this.output.push('# Check Point Management CLI Script');
        this.output.push('# Generated by UnifiedMigrator');
        this.output.push('');

        // Address Objects
        this.output.push('# --- Address Objects ---');
        (this.data.addresses || []).forEach(addr => {
            if (addr.type === 'ip-netmask' || addr.type === 'ip-mask') {
                const val = addr.value || '';
                if (val.includes('/')) {
                    const [ip, cidr] = val.split('/');
                    if (parseInt(cidr) === 32) {
                        this.output.push(`add host name "${addr.name}" ip-address "${ip}"`);
                    } else {
                        this.output.push(`add network name "${addr.name}" subnet4 "${ip}" mask-length4 "${cidr}"`);
                    }
                } else {
                    this.output.push(`add host name "${addr.name}" ip-address "${val}"`);
                }
            } else if (addr.type === 'fqdn') {
                this.output.push(`add dns-domain name "${addr.name}" is-sub-domain false`);
                this.output.push(`# FQDN value: ${addr.value}`);
            } else if (addr.type === 'ip-range') {
                const parts = (addr.value || '').split('-');
                if (parts.length === 2) {
                    this.output.push(`add address-range name "${addr.name}" ip-address-first "${parts[0]}" ip-address-last "${parts[1]}"`);
                }
            }

            if (addr.exceptions && addr.exceptions.length > 0) {
                this.output.push(`# EXCEPTIONS for ${addr.name}: ${addr.exceptions.map(e => e.reason).join('; ')}`);
            }
        });
        this.output.push('');

        // Address Groups
        this.output.push('# --- Address Groups ---');
        (this.data.addressGroups || []).forEach(grp => {
            this.output.push(`add group name "${grp.name}"`);
            grp.members.forEach(member => {
                this.output.push(`set group name "${grp.name}" members.add "${member}"`);
            });
        });
        this.output.push('');

        // Services
        this.output.push('# --- Services ---');
        (this.data.services || []).forEach(svc => {
            const proto = (svc.protocol || 'tcp').toLowerCase();
            if (proto === 'tcp') {
                this.output.push(`add service-tcp name "${svc.name}" port "${svc.port || '0'}"`);
            } else if (proto === 'udp') {
                this.output.push(`add service-udp name "${svc.name}" port "${svc.port || '0'}"`);
            } else {
                this.output.push(`# UNSUPPORTED SERVICE PROTOCOL: ${svc.name} (${proto})`);
            }
        });
        this.output.push('');

        // Service Groups
        if (this.data.serviceGroups && this.data.serviceGroups.length > 0) {
            this.output.push('# --- Service Groups ---');
            this.data.serviceGroups.forEach(grp => {
                this.output.push(`add service-group name "${grp.name}"`);
                grp.members.forEach(member => {
                    this.output.push(`set service-group name "${grp.name}" members.add "${member}"`);
                });
            });
            this.output.push('');
        }

        // Access Rules (Policies)
        this.output.push('# --- Access Rules ---');
        const sortedPolicies = [...(this.data.policies || [])].sort((a, b) => (a._ruleOrder || 0) - (b._ruleOrder || 0));
        sortedPolicies.forEach(rule => {
            const action = rule.action === 'allow' ? 'Accept' : 'Drop';
            const src = rule.source && rule.source[0] !== 'any' ? rule.source.map(s => `"${s}"`).join(' ') : '"Any"';
            const dst = rule.destination && rule.destination[0] !== 'any' ? rule.destination.map(d => `"${d}"`).join(' ') : '"Any"';
            const srv = rule.service && rule.service[0] !== 'any' ? rule.service.map(s => `"${s}"`).join(' ') : '"Any"';

            this.output.push(`add access-rule layer "Network" name "${rule.name}" position bottom source ${src} destination ${dst} service ${srv} action "${action}"`);

            if (rule.disabled) {
                this.output.push(`set access-rule layer "Network" rule-number bottom enabled false`);
            }

            if (rule.exceptions && rule.exceptions.length > 0) {
                this.output.push(`# EXCEPTIONS for ${rule.name}: ${rule.exceptions.map(e => e.reason).join('; ')}`);
            }
        });
        this.output.push('');

        // NAT Rules
        if (this.data.natRules && this.data.natRules.length > 0) {
            this.output.push('# --- NAT Rules ---');
            const sortedNat = [...this.data.natRules].sort((a, b) => (a._ruleOrder || 0) - (b._ruleOrder || 0));
            sortedNat.forEach(nat => {
                let cmd = `add nat-rule package "Standard" position bottom`;
                if (nat.originalPacket.srcAddress) cmd += ` original-source "${nat.originalPacket.srcAddress}"`;
                if (nat.originalPacket.dstAddress) cmd += ` original-destination "${nat.originalPacket.dstAddress}"`;
                if (nat.translatedPacket.srcAddress) cmd += ` translated-source "${nat.translatedPacket.srcAddress}"`;
                if (nat.translatedPacket.dstAddress) cmd += ` translated-destination "${nat.translatedPacket.dstAddress}"`;

                if (nat.natType === 'static' || nat.natType === 'static_bidirectional') {
                    cmd += ` method "static"`;
                } else if (nat.natType === 'dynamic' || nat.natType === 'pat' || nat.natType === 'pat_interface' || nat.natType === 'dynamic_ippool') {
                    cmd += ` method "hide"`;
                } else {
                    cmd += ` method "static"`;
                    this.output.push(`# WARNING: NAT type '${nat.natType}' mapped to static as best effort`);
                }

                this.output.push(cmd);

                if (nat.exceptions && nat.exceptions.length > 0) {
                    this.output.push(`# EXCEPTIONS for ${nat.name}: ${nat.exceptions.map(e => e.reason).join('; ')}`);
                }
            });
            this.output.push('');
        }

        // Static Routes
        if (this.data.staticRoutes && this.data.staticRoutes.length > 0) {
            this.output.push('# --- Static Routes ---');
            this.data.staticRoutes.forEach(route => {
                this.output.push(`# Route: ${route.name} -> ${route.destination} via ${route.nexthop} (interface: ${route.interface || 'N/A'})`);
            });
        }

        this.output.push('');
        this.output.push('publish');

        return this.output.join('\n');
    }
}
