/**
 * Cisco ASA Output Generator — Enhanced
 * Reads the upgraded IR schema and generates Cisco ASA CLI configuration.
 */

export class OutputCiscoGenerator {
    constructor(parsedData) {
        this.data = parsedData;
        this.output = [];
    }

    generate() {
        this.output.push('! Cisco ASA Configuration');
        this.output.push('! Generated by UnifiedMigrator');
        this.output.push('');

        // Address Objects
        (this.data.addresses || []).forEach(addr => {
            const safeName = addr.name.replace(/ /g, '_');
            this.output.push(`object network ${safeName}`);
            if (addr.type === 'ip-netmask' || addr.type === 'ip-mask') {
                const parts = (addr.value || '').split('/');
                if (parts.length === 2) {
                    const cidr = parseInt(parts[1]);
                    if (cidr === 32) {
                        this.output.push(` host ${parts[0]}`);
                    } else {
                        this.output.push(` subnet ${parts[0]} ${this._cidrToMask(cidr)}`);
                    }
                } else if (addr.value && addr.value.includes(' ')) {
                    this.output.push(` subnet ${addr.value}`);
                } else {
                    this.output.push(` host ${addr.value}`);
                }
            } else if (addr.type === 'fqdn') {
                this.output.push(` fqdn ${addr.value}`);
            } else if (addr.type === 'ip-range') {
                this.output.push(` range ${(addr.value || '').replace('-', ' ')}`);
            }
            if (addr.description) {
                this.output.push(` description ${addr.description}`);
            }
            if (addr.exceptions && addr.exceptions.length > 0) {
                this.output.push(` description EXCEPTIONS: ${addr.exceptions.map(e => e.reason).join('; ')}`);
            }
        });
        this.output.push('');

        // Address Groups
        (this.data.addressGroups || []).forEach(grp => {
            const safeName = grp.name.replace(/ /g, '_');
            this.output.push(`object-group network ${safeName}`);
            grp.members.forEach(member => {
                this.output.push(` network-object object ${member.replace(/ /g, '_')}`);
            });
            if (grp.description) {
                this.output.push(` description ${grp.description}`);
            }
        });
        this.output.push('');

        // Services
        (this.data.services || []).forEach(svc => {
            const safeName = svc.name.replace(/ /g, '_');
            this.output.push(`object service ${safeName}`);
            const proto = (svc.protocol || 'tcp').toLowerCase();
            if (svc.port && (proto === 'tcp' || proto === 'udp')) {
                if (svc.port.includes('-')) {
                    this.output.push(` service ${proto} destination range ${svc.port.replace('-', ' ')}`);
                } else {
                    this.output.push(` service ${proto} destination eq ${svc.port}`);
                }
            }
        });
        this.output.push('');

        // Service Groups
        (this.data.serviceGroups || []).forEach(grp => {
            const safeName = grp.name.replace(/ /g, '_');
            this.output.push(`object-group service ${safeName}`);
            grp.members.forEach(member => {
                this.output.push(` service-object object ${member.replace(/ /g, '_')}`);
            });
        });
        this.output.push('');

        // Access Lists (Policies)
        this.output.push('! Access Control Lists');
        const sortedPolicies = [...(this.data.policies || [])].sort((a, b) => (a._ruleOrder || 0) - (b._ruleOrder || 0));
        sortedPolicies.forEach(rule => {
            const action = rule.action === 'allow' ? 'permit' : 'deny';
            const src = rule.source && rule.source[0] !== 'any' ? `object-group ${rule.source[0]}` : 'any';
            const dst = rule.destination && rule.destination[0] !== 'any' ? `object-group ${rule.destination[0]}` : 'any';
            const srv = rule.service && rule.service[0] !== 'any' ? `object-group ${rule.service[0]}` : 'ip';

            this.output.push(`access-list MIGRATED_ACL extended ${action} ${srv} ${src} ${dst}`);
            if (rule.logEnd) {
                this.output.push(`access-list MIGRATED_ACL extended ${action} ${srv} ${src} ${dst} log`);
            }
        });
        this.output.push('');

        // NAT Rules
        if (this.data.natRules && this.data.natRules.length > 0) {
            this.output.push('! NAT Rules');
            const sortedNat = [...this.data.natRules].sort((a, b) => (a._ruleOrder || 0) - (b._ruleOrder || 0));
            sortedNat.forEach(nat => {
                const srcZone = nat.originalPacket.srcZone || 'inside';
                const dstZone = nat.originalPacket.dstZone || 'outside';

                if (nat.natType === 'static' || nat.natType === 'static_bidirectional') {
                    this.output.push(`nat (${srcZone},${dstZone}) source static ${nat.originalPacket.srcAddress || 'any'} ${nat.translatedPacket.srcAddress || 'any'}`);
                } else if (nat.natType === 'pat_interface') {
                    this.output.push(`nat (${srcZone},${dstZone}) source dynamic ${nat.originalPacket.srcAddress || 'any'} interface`);
                } else if (nat.natType === 'dynamic' || nat.natType === 'dynamic_ippool') {
                    this.output.push(`nat (${srcZone},${dstZone}) source dynamic ${nat.originalPacket.srcAddress || 'any'} ${nat.translatedPacket.srcAddress || 'any'}`);
                } else if (nat.natType === 'pat') {
                    this.output.push(`nat (${srcZone},${dstZone}) source dynamic ${nat.originalPacket.srcAddress || 'any'} pat-pool ${nat.translatedPacket.srcAddress || 'any'}`);
                } else {
                    this.output.push(`! UNSUPPORTED NAT TYPE: ${nat.natType} for ${nat.name}`);
                }
            });
        }

        // Static Routes
        if (this.data.staticRoutes && this.data.staticRoutes.length > 0) {
            this.output.push('');
            this.output.push('! Static Routes');
            this.data.staticRoutes.forEach(route => {
                const [ip, cidr] = (route.destination || '0.0.0.0/0').split('/');
                this.output.push(`route ${route.interface || 'outside'} ${ip} ${this._cidrToMask(parseInt(cidr || '0'))} ${route.nexthop} ${route.metric || '1'}`);
            });
        }

        return this.output.join('\n');
    }

    _cidrToMask(cidr) {
        let mask = [];
        for (let i = 0; i < 4; i++) {
            let n = Math.min(cidr, 8);
            mask.push(256 - Math.pow(2, 8 - n));
            cidr -= n;
        }
        return mask.join('.');
    }
}
