import type { Article } from '@/data/articles';

export type BlogSeoEntry = Pick<Article, 'slug' | 'title' | 'excerpt' | 'category' | 'date' | 'readTime'> & {
  metaTitle: string;
  image?: string;
};

export const blogSeoEntries: BlogSeoEntry[] = [
  {
    slug: 'identity-is-the-new-security-perimeter-itdr',
    metaTitle: 'ITDR and Identity Analytics | The Cyber Adviser',
    title: 'Identity Threat Detection and Response for Modern SOCs',
    excerpt: 'Learn how ITDR and identity analytics help security teams detect credential abuse, privilege escalation, and lateral movement across cloud and SaaS environments.',
    category: 'CORTEX XDR',
    date: '2026-04-18',
    readTime: '12 min read',
    image: '/images/blogs/itdr/itdr-attack-vs-detection.png',
  },
  {
    slug: 'cloud-native-application-platform-securing-from-code-to-cloud',
    metaTitle: 'CNAPP Security from Code to Cloud | The Cyber Adviser',
    title: 'Cloud Native Application Protection from Code to Cloud',
    excerpt: 'A practical CNAPP guide for securing code, pipelines, containers, Kubernetes, cloud posture, and runtime workloads in one operating model.',
    category: 'PRISMA SASE',
    date: '2026-04-17',
    readTime: '10 min read',
    image: '/images/blogs/cnapp/cnapp-code-to-cloud.png',
  },
  {
    slug: 'cortex-xsoar-transforming-soc-operations',
    metaTitle: 'Cortex XSOAR SOC Automation Guide | The Cyber Adviser',
    title: 'Cortex XSOAR for Modern SOC Automation',
    excerpt: 'Explore how Cortex XSOAR helps SOC teams orchestrate tools, automate enrichment, reduce manual triage, and respond to incidents faster.',
    category: 'XSOAR',
    date: '2026-04-15',
    readTime: '10 min read',
    image: '/images/blogs/cortex-xsoar/xsoar-diagram-horizontal.png',
  },
  {
    slug: 'securing-agentic-endpoint-cortex-xdr',
    metaTitle: 'Agentic Endpoint Security with Cortex XDR',
    title: 'Securing Agentic Endpoints with Cortex XDR',
    excerpt: 'Understand the new endpoint risk created by AI agents and how Cortex XDR visibility, analytics, and response controls reduce autonomous attack paths.',
    category: 'CORTEX XDR',
    date: '2026-04-12',
    readTime: '10 min read',
  },
  {
    slug: 'quantum-computing-cybersecurity-readiness',
    metaTitle: 'Quantum Cybersecurity Readiness Guide',
    title: 'Quantum Computing Cybersecurity Readiness',
    excerpt: 'Prepare for post-quantum risk by inventorying encryption, prioritizing long-life data, and building crypto-agility before harvest-now-decrypt-later attacks mature.',
    category: 'Cryptography',
    date: '2026-04-10',
    readTime: '12 min read',
    image: '/images/blogs/quantum-computing/quantum-shield.png',
  },
  {
    slug: 'what-is-palo-alto-networks-cortex-cloud',
    metaTitle: 'Palo Alto Cortex Cloud Guide',
    title: 'What Is Palo Alto Networks Cortex Cloud?',
    excerpt: 'A technical explanation of Cortex Cloud, CNAPP, cloud detection and response, attack path analysis, and SOC workflow integration.',
    category: 'CORTEX CLOUD',
    date: '2026-04-08',
    readTime: '14 min read',
    image: '/images/blogs/cortex-cloud/1.png',
  },
  {
    slug: 'strata-next-gen-firewalls',
    metaTitle: 'Strata NGFW Architecture Guide',
    title: 'Strata Next-Generation Firewall Architecture',
    excerpt: 'Design stronger Palo Alto Networks Strata NGFW deployments with App-ID policy, User-ID context, decryption planning, and threat prevention tuning.',
    category: 'STRATA NGFW',
    date: '2024-03-12',
    readTime: '8 min read',
  },
  {
    slug: 'panorama-centralized-mastery',
    metaTitle: 'Panorama Firewall Management Guide',
    title: 'Panorama Centralized Firewall Management',
    excerpt: 'Learn how to structure templates, device groups, policy hierarchy, logging, and change control for scalable Panorama operations.',
    category: 'STRATA NGFW',
    date: '2024-03-08',
    readTime: '8 min read',
  },
  {
    slug: 'prisma-access-sase-revolution',
    metaTitle: 'Prisma Access SASE Design Guide',
    title: 'Prisma Access and the SASE Architecture Shift',
    excerpt: 'Plan Prisma Access SASE transformation with mobile user design, service connections, remote networks, routing, and operational readiness.',
    category: 'PRISMA SASE',
    date: '2024-03-04',
    readTime: '8 min read',
  },
  {
    slug: 'cortex-xdr-ai-defense',
    metaTitle: 'Cortex XDR AI Defense Guide',
    title: 'Cortex XDR for AI-Driven Threat Defense',
    excerpt: 'Use Cortex XDR to correlate endpoint, network, cloud, and identity telemetry so analysts can detect advanced threats with higher fidelity.',
    category: 'CORTEX XDR',
    date: '2024-02-28',
    readTime: '8 min read',
  },
  {
    slug: 'automating-soc-xsoar',
    metaTitle: 'Automating SOC Workflows with XSOAR',
    title: 'Automating SOC Response with Cortex XSOAR',
    excerpt: 'Build XSOAR playbooks for alert enrichment, phishing triage, endpoint containment, ticketing, and repeatable incident response workflows.',
    category: 'XSOAR',
    date: '2024-02-24',
    readTime: '8 min read',
  },
  {
    slug: 'prisma-sd-wan-cloud-gen',
    metaTitle: 'Prisma SD-WAN CloudGenix Guide',
    title: 'Prisma SD-WAN CloudGenix Design Patterns',
    excerpt: 'Design application-aware SD-WAN policies, SLA path selection, branch resilience, and Prisma Access integration for modern SASE edges.',
    category: 'PRISMA SASE',
    date: '2024-02-20',
    readTime: '8 min read',
  },
  {
    slug: 'future-secops-xsiam',
    metaTitle: 'XSIAM and the Future of SecOps',
    title: 'The Future of Security Operations with XSIAM',
    excerpt: 'Explore how Cortex XSIAM changes security operations through normalized telemetry, analytics, automation, and case-driven response.',
    category: 'CORTEX XSIAM',
    date: '2024-02-18',
    readTime: '8 min read',
  },
  {
    slug: 'prisma-sase-convergence',
    metaTitle: 'Prisma SASE Convergence Guide',
    title: 'Prisma SASE Convergence for Branch and Remote Access',
    excerpt: 'Understand how Prisma Access and Prisma SD-WAN converge networking and security into one architecture for users, branches, and cloud apps.',
    category: 'PRISMA SASE',
    date: '2024-02-16',
    readTime: '8 min read',
  },
  {
    slug: 'legacy-vpn-to-ztna-the-migration-plan',
    metaTitle: 'Legacy VPN to ZTNA Migration Plan',
    title: 'From Legacy VPN to ZTNA: A Phased Migration Strategy',
    excerpt: 'A practical roadmap for transitioning from traditional VPN infrastructure to Zero Trust Network Access without disrupting business operations.',
    category: 'Zero Trust',
    date: '2024-02-15',
    readTime: '15 min read',
  },
  {
    slug: 'cloud-security-posture-management',
    metaTitle: 'CSPM Implementation Guide',
    title: 'CSPM Implementation: Building Continuous Cloud Visibility',
    excerpt: 'Deploy and operationalize Cloud Security Posture Management to maintain compliance and reduce risk across multi-cloud environments.',
    category: 'Cloud Security',
    date: '2024-02-01',
    readTime: '11 min read',
  },
  {
    slug: 'security-architecture-review-methodology',
    metaTitle: 'Security Architecture Review Methodology',
    title: 'Security Architecture Review: A Structured Assessment Methodology',
    excerpt: 'A practical framework for assessing enterprise security architecture, identifying gaps, and building a prioritized remediation roadmap.',
    category: 'Architecture',
    date: '2024-01-20',
    readTime: '14 min read',
  },
];

export const blogSlugs = blogSeoEntries.map((entry) => entry.slug);

export function getBlogSeoEntry(slug: string) {
  return blogSeoEntries.find((entry) => entry.slug === slug);
}
