import type { SiemPlatformConfig, SiemPlatformKey } from '@/types/siem-sizing';

export const DEFAULT_RETENTION_DAYS = 90;
export const DEFAULT_COMPRESSION_RATIO = 7;

export const SIEM_PLATFORM_CONFIG: Record<SiemPlatformKey, SiemPlatformConfig> = {
  wazuh: {
    label: 'Wazuh',
    shortLabel: 'W',
    summary: 'Open-source SIEM with practical single-node and distributed paths.',
    employeeAgentFactor: 0.2,
    networkAgentFactor: 0.35,
    endpointGbPerDay: 0.04,
    serverGbPerDay: 0.12,
    networkGbPerDay: 0.5,
    cloudGbPerDay: 0.8,
  },
  splunk: {
    label: 'Splunk Enterprise',
    shortLabel: 'S',
    summary: 'Higher ingest density with stronger infrastructure requirements.',
    employeeAgentFactor: 0.24,
    networkAgentFactor: 0.4,
    endpointGbPerDay: 0.06,
    serverGbPerDay: 0.18,
    networkGbPerDay: 0.7,
    cloudGbPerDay: 1,
  },
  qradar: {
    label: 'IBM QRadar',
    shortLabel: 'Q',
    summary: 'Balanced collector and storage sizing for traditional SOC deployments.',
    employeeAgentFactor: 0.18,
    networkAgentFactor: 0.3,
    endpointGbPerDay: 0.05,
    serverGbPerDay: 0.15,
    networkGbPerDay: 0.6,
    cloudGbPerDay: 0.9,
  },
  sentinel: {
    label: 'Microsoft Sentinel',
    shortLabel: 'MS',
    summary: 'Cloud-oriented analytics profile with moderate per-source growth.',
    employeeAgentFactor: 0.22,
    networkAgentFactor: 0.3,
    endpointGbPerDay: 0.05,
    serverGbPerDay: 0.16,
    networkGbPerDay: 0.65,
    cloudGbPerDay: 0.9,
  },
  logrhythm: {
    label: 'LogRhythm',
    shortLabel: 'LR',
    summary: 'Traditional SIEM footprint tuned for moderate enterprise estates.',
    employeeAgentFactor: 0.18,
    networkAgentFactor: 0.28,
    endpointGbPerDay: 0.05,
    serverGbPerDay: 0.14,
    networkGbPerDay: 0.55,
    cloudGbPerDay: 0.85,
  },
  graylog: {
    label: 'Graylog',
    shortLabel: 'G',
    summary: 'Elastic-style log analytics with efficient storage ratios.',
    employeeAgentFactor: 0.18,
    networkAgentFactor: 0.32,
    endpointGbPerDay: 0.045,
    serverGbPerDay: 0.13,
    networkGbPerDay: 0.52,
    cloudGbPerDay: 0.82,
  },
  cortexxsoar: {
    label: 'Cortex XSOAR',
    shortLabel: 'CX',
    summary: 'Automation-centric deployment profile with lighter ingest assumptions.',
    employeeAgentFactor: 0.16,
    networkAgentFactor: 0.22,
    endpointGbPerDay: 0.035,
    serverGbPerDay: 0.1,
    networkGbPerDay: 0.4,
    cloudGbPerDay: 0.7,
  },
};

export const SIEM_PLATFORM_ORDER: SiemPlatformKey[] = [
  'wazuh',
  'splunk',
  'qradar',
  'sentinel',
  'logrhythm',
  'graylog',
  'cortexxsoar',
];
